import nodemailer from 'nodemailer';
import type { Transporter } from 'nodemailer';

interface EmailOptions {
  to: string;
  subject: string;
  html: string;
  text?: string;
}

let transporter: Transporter | null = null;

function getTransporter(): Transporter {
  if (transporter) return transporter;

  const host = process.env.SMTP_HOST;
  const port = Number(process.env.SMTP_PORT) || 587;
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (host && user && pass) {
    transporter = nodemailer.createTransport({
      host,
      port,
      secure: port === 465,
      auth: { user, pass },
    });
    console.log(`✉️ Configured production SMTP transport: ${host}:${port}`);
  } else {
    // Zero-cost development mode fallback (logs nicely to console)
    transporter = nodemailer.createTransport({
      streamTransport: true,
      newline: 'unix',
      buffer: true,
    });
    console.log('✉️ Email service initialized in Zero-Cost Dev Mode (logged to console)');
  }

  return transporter;
}

export async function sendEmail({ to, subject, html, text }: EmailOptions): Promise<void> {
  try {
    const mailer = getTransporter();
    const fromAddress = process.env.SMTP_FROM || 'COOP-ITSM Service Desk <no-reply@coopbankoromia.com.et>';

    const info = await mailer.sendMail({
      from: fromAddress,
      to,
      subject,
      html,
      text: text || html.replace(/<[^>]+>/g, ' '),
    });

    if (info.message) {
      console.log(`\n📧 [EMAIL DISPATCHED: ZERO-COST LOCAL STREAM]`);
      console.log(`   To: ${to}`);
      console.log(`   Subject: ${subject}`);
      console.log(`   Date: ${new Date().toISOString()}`);
    } else {
      console.log(`✉️ Email delivered successfully to ${to} (MessageId: ${info.messageId})`);
    }
  } catch (error: any) {
    console.warn(`[EMAIL NOTICE] Unable to deliver email to ${to}:`, error?.message || error);
  }
}

// ─── Branded Banking Email Templates ──────────────────────────────────────────

function getEmailWrapper(content: string): string {
  return `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden;">
      <div style="background: #0B2545; padding: 20px 24px; color: #ffffff;">
        <h1 style="margin: 0; font-size: 20px; font-weight: 800; letter-spacing: -0.5px;">COOP-ITSM</h1>
        <p style="margin: 4px 0 0 0; font-size: 12px; color: #94a3b8;">Cooperative Bank of Oromia | Enterprise Incident Operations</p>
      </div>
      <div style="padding: 24px; color: #1e293b; font-size: 14px; line-height: 1.6;">
        ${content}
      </div>
      <div style="background: #f8fafc; padding: 16px 24px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #64748b;">
        <p style="margin: 0;">This is an automated operational notification generated by the COOP-ITSM Banking Platform.</p>
        <p style="margin: 4px 0 0 0;">Do not reply directly to this message. For escalations, contact Tier-2 IT Operations.</p>
      </div>
    </div>
  `;
}

export async function sendIncidentCreatedNotification(incident: any, recipientEmail: string, branchName: string): Promise<void> {
  const html = getEmailWrapper(`
    <h2 style="margin-top: 0; color: #0f172a; font-size: 18px;">Incident Logged: ${incident.incidentNumber}</h2>
    <p>Your branch incident has been officially logged in the system and queued for IT triage.</p>
    <table style="width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px;">
      <tr><td style="padding: 6px 0; color: #64748b;">Title:</td><td style="font-weight: 600;">${incident.title}</td></tr>
      <tr><td style="padding: 6px 0; color: #64748b;">Branch:</td><td style="font-weight: 600;">${branchName}</td></tr>
      <tr><td style="padding: 6px 0; color: #64748b;">Priority:</td><td style="font-weight: 600; color: #b91c1c;">${incident.priority}</td></tr>
      <tr><td style="padding: 6px 0; color: #64748b;">SLA Resolution Target:</td><td style="font-weight: 600;">${new Date(incident.slaDeadline).toLocaleString()}</td></tr>
    </table>
    <p>You can track resolution progress in real-time from the branch portal.</p>
  `);

  await sendEmail({
    to: recipientEmail,
    subject: `[COOP-ITSM] Incident Logged: ${incident.incidentNumber} - ${incident.title}`,
    html,
  });
}

export async function sendIncidentAssignedNotification(incident: any, technicianEmail: string, technicianName: string): Promise<void> {
  const html = getEmailWrapper(`
    <h2 style="margin-top: 0; color: #0f172a; font-size: 18px;">Work Order Assigned: ${incident.incidentNumber}</h2>
    <p>Hello <strong>${technicianName}</strong>,</p>
    <p>You have been assigned to resolve the following banking incident:</p>
    <table style="width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px;">
      <tr><td style="padding: 6px 0; color: #64748b;">Incident No:</td><td style="font-weight: 600;">${incident.incidentNumber}</td></tr>
      <tr><td style="padding: 6px 0; color: #64748b;">Title:</td><td style="font-weight: 600;">${incident.title}</td></tr>
      <tr><td style="padding: 6px 0; color: #64748b;">Priority:</td><td style="font-weight: 600; color: #b91c1c;">${incident.priority}</td></tr>
      <tr><td style="padding: 6px 0; color: #64748b;">Target Deadline:</td><td style="font-weight: 600;">${new Date(incident.slaDeadline).toLocaleString()}</td></tr>
    </table>
    <p>Please launch your <strong>Technician Workbench</strong> to begin diagnostic investigation.</p>
  `);

  await sendEmail({
    to: technicianEmail,
    subject: `[COOP-ITSM] Assigned: ${incident.incidentNumber} [${incident.priority}]`,
    html,
  });
}

export async function sendIncidentResolvedNotification(incident: any, recipientEmail: string): Promise<void> {
  const html = getEmailWrapper(`
    <h2 style="margin-top: 0; color: #0f172a; font-size: 18px;">Incident Marked Resolved: ${incident.incidentNumber}</h2>
    <p>The assigned IT technician has marked incident <strong>${incident.incidentNumber}</strong> as resolved.</p>
    <table style="width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px;">
      <tr><td style="padding: 6px 0; color: #64748b;">Title:</td><td style="font-weight: 600;">${incident.title}</td></tr>
      <tr><td style="padding: 6px 0; color: #64748b;">Root Cause:</td><td style="font-weight: 600;">${incident.rootCause || 'Identified and repaired'}</td></tr>
      <tr><td style="padding: 6px 0; color: #64748b;">Resolution:</td><td style="font-weight: 600;">${incident.resolution || 'Service restored'}</td></tr>
    </table>
    <p><strong>Action Required:</strong> Please sign in to your branch portal to confirm service restoration and verify ticket closure.</p>
  `);

  await sendEmail({
    to: recipientEmail,
    subject: `[COOP-ITSM] Resolved: ${incident.incidentNumber} - Action Required`,
    html,
  });
}

export async function sendSlaBreachEscalationNotification(incident: any, supervisorEmail: string): Promise<void> {
  const html = getEmailWrapper(`
    <div style="border-left: 4px solid #ef4444; padding-left: 12px; margin-bottom: 16px;">
      <h2 style="margin: 0; color: #b91c1c; font-size: 18px;">URGENT: SLA Breach Escalation</h2>
      <p style="margin: 4px 0 0 0; font-size: 12px; color: #64748b;">Incident ${incident.incidentNumber} has exceeded its operational SLA target.</p>
    </div>
    <p>Supervisor attention is required immediately for priority reallocation:</p>
    <table style="width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px;">
      <tr><td style="padding: 6px 0; color: #64748b;">Incident No:</td><td style="font-weight: 600;">${incident.incidentNumber}</td></tr>
      <tr><td style="padding: 6px 0; color: #64748b;">Title:</td><td style="font-weight: 600;">${incident.title}</td></tr>
      <tr><td style="padding: 6px 0; color: #64748b;">Current Status:</td><td style="font-weight: 600;">${incident.status}</td></tr>
      <tr><td style="padding: 6px 0; color: #64748b;">Priority:</td><td style="font-weight: 600; color: #b91c1c;">${incident.priority}</td></tr>
      <tr><td style="padding: 6px 0; color: #64748b;">Expired Deadline:</td><td style="font-weight: 600;">${new Date(incident.slaDeadline).toLocaleString()}</td></tr>
    </table>
  `);

  await sendEmail({
    to: supervisorEmail,
    subject: `[COOP-ITSM] SLA BREACH ALERT: ${incident.incidentNumber} [${incident.priority}]`,
    html,
  });
}

